### ISSUE TITLE
version solving failed.

### ISSUE THREAD

**Issue by Jules369-ZM** [matanshukry/flutter_google_places_sdk#86] opened 2024-06-10 08:48 UTC
Because fluttercontactpicker >=5.0.0 depends on contact_picker_web ^5.0.0 which depends on js ^0.7.1,
  fluttercontactpicker >=5.0.0 requires js ^0.7.1.
And because flutter_google_places_sdk >=0.3.9 depends on flutter_google_places_sdk_web ^0.1.7 which
  depends on js ^0.6.7, fluttercontactpicker >=5.0.0 is incompatible with flutter_google_places_sdk
  >=0.3.9.
So, because unka depends on both flutter_google_places_sdk ^0.3.9 and fluttercontactpicker ^5.0.0,
  version solving failed.

**Comment by matanshukry** [comment] 2024-08-14 08:41
@Jules369-ZM tl&dr: in progress

This requires us to upgrade the js dependency, which was impossible due to google_maps dependency - even wrote a comment in pubspec.yaml

However google_maps has new version and once upgraded we can also upgrade js
Will update soon

**Comment by matanshukry** [comment] 2024-08-14 20:07
Just realized it's a duplicate of https://github.com/matanshukry/flutter_google_places_sdk/issues/86 - closing this, will keep track there

**Closed by matanshukry** 2024-08-14 20:07 UTC
Labels: enhancement, good first issue
