### ISSUE TITLE
[iOS] Allow to provide multiple type filters for autocomplete search

### ISSUE THREAD

**Issue by TatsuUkraine** [matanshukry/flutter_google_places_sdk#48] opened 2023-05-29 11:07 UTC
Places SDK allows to provide of multiple type filters for autocomplete predictions. But current version of the package allows to provide only 1.

https://developers.google.com/maps/documentation/places/android-sdk/reference/com/google/android/libraries/places/api/net/FindAutocompletePredictionsRequest.Builder#public-abstract-findautocompletepredictionsrequest.builder-settypesfilter-liststring-typesfilter

Also, the current method setTypeFilter marked as deprecated

https://developers.google.com/maps/documentation/places/android-sdk/reference/com/google/android/libraries/places/api/net/FindAutocompletePredictionsRequest.Builder#public-abstract-findautocompletepredictionsrequest.builder-settypefilter-typefilter-typefilter

**Comment by TatsuUkraine** [comment] 2023-08-15 11:40
is this package still maintained at all?

**Comment by matanshukry** [comment] 2023-08-19 19:07
Done and published almost all versions - iOS is the only one missing since.
Leaving this open and tagging as iOS.

**Comment by TatsuUkraine** [comment] 2023-08-19 19:19
Nice! Thank you

**Comment by esuljic** [comment] 2023-09-13 10:04
I made a #57, seems like at this last release, the first is not working as well on iOS. It shows all of the results.

**Comment by ctostech** [comment] 2023-09-13 23:04
The issue is still happening on iOS, any update?

**Comment by matanshukry** [comment] 2023-09-14 06:46
I don't have a mac so I can't work on the iOS fix.
That is why everything else is working except that.

Any PR is welcome though in the meantime, and I'll try to find some solution through pc in the meantime.

**Comment by maxbritto** [comment] 2023-09-26 13:01
I've checked and in order to make this happend, we need to use the GooglePlaces swift sdk version 7.2.0 at least, which requires iOS 13 minimum.
Hence, we have to raise this library iOS minimum deployment target from iOS 11 to iOS 13.
As of this writing, iOS 13 and above represents 96,8% of the devices according to https://iosref.com/ios-usage

**Comment by maxbritto** [comment] 2023-09-26 13:10
If you want to accept it, here is the PR : https://github.com/matanshukry/flutter_google_places_sdk/pull/59

**Comment by maxbritto** [comment] 2023-09-29 13:10
@matanshukry : you can now close this one after 0.3.7

**Closed** 2023-09-29 13:11 UTC
