### ISSUE TITLE
Support JDK 17

### ISSUE THREAD

**Issue by SherpaMiguel** [matanshukry/flutter_google_places_sdk#71] opened 2024-02-07 23:18 UTC
When using Gradle 8 (requires JDK 17):

Execution failed for task ':flutter_google_places_sdk_android:compileDebugKotlin'.
'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

**Comment by larssn** [comment] 2024-03-26 12:05
@SherpaMiguel When inserting your `afterEvaluate` script into the bottom of `android/build.gradle`, I get an error on build: `Cannot run Project.afterEvaluate(Closure) when the project is already evaluated.`

**Comment by TatsuUkraine** [comment] 2024-08-16 13:56
Does anybody know when this fix may be released?

**Comment by AkashKrx** [comment] 2024-08-17 06:55
> @jonasborggren yep, add this into your android/build.gradle
> 
> ```
> subprojects {
>     afterEvaluate {
>         if (project.plugins.hasPlugin("com.android.application")
>                 || project.plugins.hasPlugin("com.android.library")) {
>             // TODO FIX
>             // https://github.com/matanshukry/flutter_google_places_sdk/issues/71
>             if (project.name == "flutter_google_places_sdk_android") {
>                 project.android.compileOptions {
>                     sourceCompatibility = JavaVersion.VERSION_17
>                     targetCompatibility = JavaVersion.VERSION_17
>                 }
>             }
>         }
>     }
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
>     project.evaluationDependsOn(':app')
> }
> ```

This solution stopped working

**Comment by matanshukry** [comment] 2024-08-17 12:44
@TatsuUkraine I've updated the build.gradle and settings.gradle due to an upgrade as part of flutter, but as I wrote before it is working for me successfully.

I'm using Gradle 8.1.1 , Java 19.0.2, and flutter 3.24.0.

**Comment by TatsuUkraine** [comment] 2024-08-17 12:55
So I was recently updating project to AGP 8.3.1, due to an r8 issue. Which forced me to switch to java17. I'm on flutter 3.22 still though.

Workaround described here https://github.com/matanshukry/flutter_google_places_sdk/issues/71#issuecomment-1933800376 worked for me as a tmp solution.

I also noticed referenced PR in this thread, which got merged, but it seems new version with this fix wasn't released yet

**Comment by TatsuUkraine** [comment] 2024-08-17 12:58
The error I'm getting prior tmp fix was exactly the one described in the description of this ticket

**Comment by matanshukry** [comment] 2024-08-17 13:01
@TatsuUkraine As far as I can tell the temporary solution described here is part of users/your project not part of this plugin, so it shouldn't be related.

Try to provide more details or even a reproducible repo/example so I can reproduce the error on my end, and hence fix any issues if there are any

**Comment by TatsuUkraine** [comment] 2024-08-17 13:12
@matanshukry https://github.com/matanshukry/flutter_google_places_sdk/pull/82

**Comment by matanshukry** [comment] 2024-08-17 13:14
> @matanshukry #82

That PR is not a reproducible example; it doesn't even talk about the problem.

Also it was already merged, so I don't even understand what's your point...

**Comment by TatsuUkraine** [comment] 2024-08-17 13:19
@matanshukry sorry, didn't write full message ( I meant that this PR got merged, but these changes was never released. As part of this changes I can see that it switches plugin to use java 17

**Comment by matanshukry** [comment] 2024-08-17 13:22
@TatsuUkraine oh ok that make sense.
Let me look into that then

**Comment by TatsuUkraine** [comment] 2024-08-17 13:24
I can be wrong here, but as far as I understand in order to switch to AGP 8 all your third party deps, as well as the project, should target the same jvm version, and the tmp fix in this thread does it by forcing current package have the same java version configs

**Comment by TatsuUkraine** [comment] 2024-08-17 13:28
I have so many third party deps, so I can assume some of them does switch back and forward between jvm versions during the build, which ends up with the fail due to race condition in the Gradle build 😅 so I did just easiest thing so far - override compile options to match my project compile options for Google maps package and it worked))

**Comment by matanshukry** [comment] 2024-08-17 14:27
@TatsuUkraine Published to 0.1.9 .
Should take few minutes, but then please try it and let me know if it solves the issue

**Comment by TatsuUkraine** [comment] 2024-08-17 18:06
@matanshukry thank you, I will let you know if anything comes up

**Comment by matanshukry** [comment] 2024-08-17 22:52
Closing for now then, will re-open if needed

**Closed by matanshukry** 2024-08-17 22:52 UTC
Labels: waiting for feedback

**Comment by TatsuUkraine** [comment] 2024-08-17 23:32
@matanshukry looks good on my end, builds are passing without the tmp fix
